### ISSUE TITLE
Erro ao executar comando protoc

### ISSUE THREAD

**Issue by heroneto** [codeedu/imersao-7-codepix#3]
https://github.com/codeedu/imersao-7-codepix/blob/b7ed410caae49875c8112aa1af1ef81063ad0a0b/codepix/application/grpc/protofiles/pixkey.proto#L5

Quando executo o comando protoc ocorre o erro abaixo:
`The import path must contain at least one period ('.') or forward slash ('/') character. `

Encontrei uma solução. Caso ocorra erro ao executar o comando protoc, é necessário add o ./ antes do `protofiles;pb` . Da seguinte forma:

`option go_package = "./protofiles;pb";`

**Comment by henriqueholtz** [comment]
Olá @heroneto tudo bem? A correção é bem simples como citado no [pull request](https://github.com/codeedu/imersao-7-codepix/pull/4).

Também expliquei no comentário do [video](https://www.youtube.com/watch?v=DP9zfx-7ChA)
